name: questbee
description: Questions to ponder and discuss.

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_design_icons_flutter: 3.2.3695

  cupertino_icons: ^0.1.2

  uni_links: ^0.2.0
  url_launcher: ^5.0.2
  draw: ^0.5.1
  flutter_secure_storage: ^3.2.1

  after_layout: ^1.0.7

  redux: ^3.0.0
  redux_thunk: ^0.2.1
  flutter_redux: ^0.5.3
  flutter_redux_navigation: ^0.4.1

  provider: ^2.0.1

  dio: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
