name: questbee
description: Questions to ponder and discuss.

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  material_design_icons_flutter: 3.2.3695
  cupertino_icons: ^0.1.2
  grouped_buttons: ^1.0.4
  pull_to_refresh: ^1.4.3
  flutter_markdown: ^0.2.0

  # Authentication
  uni_links: ^0.2.0
  url_launcher: ^5.0.2
  flutter_secure_storage: ^3.2.1
  firebase_auth: ^0.11.1

  # Network
  draw: ^0.5.2
  dio: ^2.1.6
  cached_network_image: ^0.8.0

  # State Management
  redux: ^3.0.0
  redux_thunk: ^0.2.1
  flutter_redux: ^0.5.3
  flutter_redux_navigation: ^0.4.1
  redux_persist: ^0.8.2
  redux_epics: ^0.10.6
  rxdart: ^0.22.0
  provider: ^2.0.1

  # Notifications
  firebase_messaging: ^5.0.2
  flutter_local_notifications: ^0.7.1

  # Firebase Analytics
  firebase_analytics: ^3.0.2
  firebase_crashlytics: ^0.0.4
  firebase_performance: ^0.3.0

  # Backend access
  cloud_firestore: ^0.12.5
  cloud_functions: ^0.4.0

  # Easy immutable values & serialization
  built_value: ^6.6.0

  # Misc
  after_layout: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.5.2
  built_value_generator: ^6.6.0

flutter:
  uses-material-design: true
